// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: se_app.proto

package seapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	StageType     string                 `protobuf:"bytes,2,opt,name=stage_type,json=stageType,proto3" json:"stage_type,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,4,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	TaskIri       string                 `protobuf:"bytes,5,opt,name=task_iri,json=taskIri,proto3" json:"task_iri,omitempty"`
	LlmApiKey     string                 `protobuf:"bytes,6,opt,name=llm_api_key,json=llmApiKey,proto3" json:"llm_api_key,omitempty"`
	LlmBaseUrl    string                 `protobuf:"bytes,7,opt,name=llm_base_url,json=llmBaseUrl,proto3" json:"llm_base_url,omitempty"`
	LlmModel      string                 `protobuf:"bytes,8,opt,name=llm_model,json=llmModel,proto3" json:"llm_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStageRequest) Reset() {
	*x = ExecuteStageRequest{}
	mi := &file_se_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStageRequest) ProtoMessage() {}

func (x *ExecuteStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ExecuteStageRequest) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteStageRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ExecuteStageRequest) GetStageType() string {
	if x != nil {
		return x.StageType
	}
	return ""
}

func (x *ExecuteStageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteStageRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ExecuteStageRequest) GetTaskIri() string {
	if x != nil {
		return x.TaskIri
	}
	return ""
}

func (x *ExecuteStageRequest) GetLlmApiKey() string {
	if x != nil {
		return x.LlmApiKey
	}
	return ""
}

func (x *ExecuteStageRequest) GetLlmBaseUrl() string {
	if x != nil {
		return x.LlmBaseUrl
	}
	return ""
}

func (x *ExecuteStageRequest) GetLlmModel() string {
	if x != nil {
		return x.LlmModel
	}
	return ""
}

type ExecuteStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	OutputJson    []byte                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	OutputIri     string                 `protobuf:"bytes,4,opt,name=output_iri,json=outputIri,proto3" json:"output_iri,omitempty"`
	Artifacts     []string               `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Errors        []string               `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStageResponse) Reset() {
	*x = ExecuteStageResponse{}
	mi := &file_se_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStageResponse) ProtoMessage() {}

func (x *ExecuteStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ExecuteStageResponse) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteStageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteStageResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ExecuteStageResponse) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

func (x *ExecuteStageResponse) GetOutputIri() string {
	if x != nil {
		return x.OutputIri
	}
	return ""
}

func (x *ExecuteStageResponse) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ExecuteStageResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputIri     string                 `protobuf:"bytes,1,opt,name=output_iri,json=outputIri,proto3" json:"output_iri,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	OutputJson    []byte                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateContractRequest) Reset() {
	*x = ValidateContractRequest{}
	mi := &file_se_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateContractRequest) ProtoMessage() {}

func (x *ValidateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ValidateContractRequest) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateContractRequest) GetOutputIri() string {
	if x != nil {
		return x.OutputIri
	}
	return ""
}

func (x *ValidateContractRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *ValidateContractRequest) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

type ValidateContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateContractResponse) Reset() {
	*x = ValidateContractResponse{}
	mi := &file_se_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateContractResponse) ProtoMessage() {}

func (x *ValidateContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ValidateContractResponse) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateContractResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateContractResponse) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

type FlattenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iri           string                 `protobuf:"bytes,1,opt,name=iri,proto3" json:"iri,omitempty"`
	FrameType     string                 `protobuf:"bytes,2,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlattenRequest) Reset() {
	*x = FlattenRequest{}
	mi := &file_se_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlattenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlattenRequest) ProtoMessage() {}

func (x *FlattenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*FlattenRequest) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{4}
}

func (x *FlattenRequest) GetIri() string {
	if x != nil {
		return x.Iri
	}
	return ""
}

func (x *FlattenRequest) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

type FlattenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontendJson  string                 `protobuf:"bytes,1,opt,name=frontend_json,json=frontendJson,proto3" json:"frontend_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlattenResponse) Reset() {
	*x = FlattenResponse{}
	mi := &file_se_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlattenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlattenResponse) ProtoMessage() {}

func (x *FlattenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*FlattenResponse) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{5}
}

func (x *FlattenResponse) GetFrontendJson() string {
	if x != nil {
		return x.FrontendJson
	}
	return ""
}

type SubmitApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StageId       string                 `protobuf:"bytes,3,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Approved      bool                   `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	Comments      string                 `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	Reviewer      string                 `protobuf:"bytes,6,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApprovalRequest) Reset() {
	*x = SubmitApprovalRequest{}
	mi := &file_se_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApprovalRequest) ProtoMessage() {}

func (x *SubmitApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SubmitApprovalRequest) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitApprovalRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitApprovalRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SubmitApprovalRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *SubmitApprovalRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *SubmitApprovalRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *SubmitApprovalRequest) GetReviewer() string {
	if x != nil {
		return x.Reviewer
	}
	return ""
}

type SubmitApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApprovalResponse) Reset() {
	*x = SubmitApprovalResponse{}
	mi := &file_se_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApprovalResponse) ProtoMessage() {}

func (x *SubmitApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SubmitApprovalResponse) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitApprovalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitApprovalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	TaskIri       string                 `protobuf:"bytes,2,opt,name=task_iri,json=taskIri,proto3" json:"task_iri,omitempty"`
	LlmApiKey     string                 `protobuf:"bytes,3,opt,name=llm_api_key,json=llmApiKey,proto3" json:"llm_api_key,omitempty"`
	LlmBaseUrl    string                 `protobuf:"bytes,4,opt,name=llm_base_url,json=llmBaseUrl,proto3" json:"llm_base_url,omitempty"`
	LlmModel      string                 `protobuf:"bytes,5,opt,name=llm_model,json=llmModel,proto3" json:"llm_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_se_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{8}
}

func (x *ChatStreamRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatStreamRequest) GetTaskIri() string {
	if x != nil {
		return x.TaskIri
	}
	return ""
}

func (x *ChatStreamRequest) GetLlmApiKey() string {
	if x != nil {
		return x.LlmApiKey
	}
	return ""
}

func (x *ChatStreamRequest) GetLlmBaseUrl() string {
	if x != nil {
		return x.LlmBaseUrl
	}
	return ""
}

func (x *ChatStreamRequest) GetLlmModel() string {
	if x != nil {
		return x.LlmModel
	}
	return ""
}

type ChatStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_se_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_se_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_se_app_proto_rawDescGZIP(), []int{9}
}

func (x *ChatStreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatStreamChunk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_se_app_proto protoreflect.FileDescriptor

const file_se_app_proto_rawDesc = "" +
	"\n" +
	"\fse_app.proto\x12\x05seapp\"\x82\x02\n" +
	"\x13ExecuteStageRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x1d\n" +
	"\n" +
	"stage_type\x18\x02 \x01(\tR\tstageType\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vproject_dir\x18\x04 \x01(\tR\n" +
	"projectDir\x12\x19\n" +
	"\btask_iri\x18\x05 \x01(\tR\ataskIri\x12\x1e\n" +
	"\vllm_api_key\x18\x06 \x01(\tR\tllmApiKey\x12 \n" +
	"\fllm_base_url\x18\a \x01(\tR\n" +
	"llmBaseUrl\x12\x1b\n" +
	"\tllm_model\x18\b \x01(\tR\bllmModel\"\xbe\x01\n" +
	"\x14ExecuteStageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\fR\n" +
	"outputJson\x12\x1d\n" +
	"\n" +
	"output_iri\x18\x04 \x01(\tR\toutputIri\x12\x1c\n" +
	"\tartifacts\x18\x05 \x03(\tR\tartifacts\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors\"z\n" +
	"\x17ValidateContractRequest\x12\x1d\n" +
	"\n" +
	"output_iri\x18\x01 \x01(\tR\toutputIri\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\fR\n" +
	"outputJson\"P\n" +
	"\x18ValidateContractResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"A\n" +
	"\x0eFlattenRequest\x12\x10\n" +
	"\x03iri\x18\x01 \x01(\tR\x03iri\x12\x1d\n" +
	"\n" +
	"frame_type\x18\x02 \x01(\tR\tframeType\"6\n" +
	"\x0fFlattenResponse\x12#\n" +
	"\rfrontend_json\x18\x01 \x01(\tR\ffrontendJson\"\xc6\x01\n" +
	"\x15SubmitApprovalRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bstage_id\x18\x03 \x01(\tR\astageId\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapproved\x12\x1a\n" +
	"\bcomments\x18\x05 \x01(\tR\bcomments\x12\x1a\n" +
	"\breviewer\x18\x06 \x01(\tR\breviewer\"L\n" +
	"\x16SubmitApprovalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x11ChatStreamRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x19\n" +
	"\btask_iri\x18\x02 \x01(\tR\ataskIri\x12\x1e\n" +
	"\vllm_api_key\x18\x03 \x01(\tR\tllmApiKey\x12 \n" +
	"\fllm_base_url\x18\x04 \x01(\tR\n" +
	"llmBaseUrl\x12\x1b\n" +
	"\tllm_model\x18\x05 \x01(\tR\bllmModel\"W\n" +
	"\x0fChatStreamChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x89\x03\n" +
	"\x0fSeKernelService\x12G\n" +
	"\fExecuteStage\x12\x1a.seapp.ExecuteStageRequest\x1a\x1b.seapp.ExecuteStageResponse\x12S\n" +
	"\x10ValidateContract\x12\x1e.seapp.ValidateContractRequest\x1a\x1f.seapp.ValidateContractResponse\x12B\n" +
	"\x11FlattenToFrontend\x12\x15.seapp.FlattenRequest\x1a\x16.seapp.FlattenResponse\x12R\n" +
	"\x13SubmitHumanApproval\x12\x1c.seapp.SubmitApprovalRequest\x1a\x1d.seapp.SubmitApprovalResponse\x12@\n" +
	"\n" +
	"ChatStream\x12\x18.seapp.ChatStreamRequest\x1a\x16.seapp.ChatStreamChunk0\x01B(Z&github.com/agent-os/se-app/proto/seappb\x06proto3"

var (
	file_se_app_proto_rawDescOnce sync.Once
	file_se_app_proto_rawDescData []byte
)

func file_se_app_proto_rawDescGZIP() []byte {
	file_se_app_proto_rawDescOnce.Do(func() {
		file_se_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_se_app_proto_rawDesc), len(file_se_app_proto_rawDesc)))
	})
	return file_se_app_proto_rawDescData
}

var file_se_app_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_se_app_proto_goTypes = []any{
	(*ExecuteStageRequest)(nil),      // 0: seapp.ExecuteStageRequest
	(*ExecuteStageResponse)(nil),     // 1: seapp.ExecuteStageResponse
	(*ValidateContractRequest)(nil),  // 2: seapp.ValidateContractRequest
	(*ValidateContractResponse)(nil), // 3: seapp.ValidateContractResponse
	(*FlattenRequest)(nil),           // 4: seapp.FlattenRequest
	(*FlattenResponse)(nil),          // 5: seapp.FlattenResponse
	(*SubmitApprovalRequest)(nil),    // 6: seapp.SubmitApprovalRequest
	(*SubmitApprovalResponse)(nil),   // 7: seapp.SubmitApprovalResponse
	(*ChatStreamRequest)(nil),        // 8: seapp.ChatStreamRequest
	(*ChatStreamChunk)(nil),          // 9: seapp.ChatStreamChunk
}
var file_se_app_proto_depIdxs = []int32{
	0, // 0: seapp.SeKernelService.ExecuteStage:input_type -> seapp.ExecuteStageRequest
	2, // 1: seapp.SeKernelService.ValidateContract:input_type -> seapp.ValidateContractRequest
	4, // 2: seapp.SeKernelService.FlattenToFrontend:input_type -> seapp.FlattenRequest
	6, // 3: seapp.SeKernelService.SubmitHumanApproval:input_type -> seapp.SubmitApprovalRequest
	8, // 4: seapp.SeKernelService.ChatStream:input_type -> seapp.ChatStreamRequest
	1, // 5: seapp.SeKernelService.ExecuteStage:output_type -> seapp.ExecuteStageResponse
	3, // 6: seapp.SeKernelService.ValidateContract:output_type -> seapp.ValidateContractResponse
	5, // 7: seapp.SeKernelService.FlattenToFrontend:output_type -> seapp.FlattenResponse
	7, // 8: seapp.SeKernelService.SubmitHumanApproval:output_type -> seapp.SubmitApprovalResponse
	9, // 9: seapp.SeKernelService.ChatStream:output_type -> seapp.ChatStreamChunk
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_se_app_proto_init() }
func file_se_app_proto_init() {
	if File_se_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_se_app_proto_rawDesc), len(file_se_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_se_app_proto_goTypes,
		DependencyIndexes: file_se_app_proto_depIdxs,
		MessageInfos:      file_se_app_proto_msgTypes,
	}.Build()
	File_se_app_proto = out.File
	file_se_app_proto_goTypes = nil
	file_se_app_proto_depIdxs = nil
}