// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.14.0
// source: se_app.proto

package seapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	SeKernelService_ExecuteStage_FullMethodName        = "/seapp.SeKernelService/ExecuteStage"
	SeKernelService_ValidateContract_FullMethodName    = "/seapp.SeKernelService/ValidateContract"
	SeKernelService_FlattenToFrontend_FullMethodName   = "/seapp.SeKernelService/FlattenToFrontend"
	SeKernelService_SubmitHumanApproval_FullMethodName = "/seapp.SeKernelService/SubmitHumanApproval"
	SeKernelService_ChatStream_FullMethodName          = "/seapp.SeKernelService/ChatStream"
)

type SeKernelServiceClient interface {
	ExecuteStage(ctx context.Context, in *ExecuteStageRequest, opts ...grpc.CallOption) (*ExecuteStageResponse, error)
	ValidateContract(ctx context.Context, in *ValidateContractRequest, opts ...grpc.CallOption) (*ValidateContractResponse, error)
	FlattenToFrontend(ctx context.Context, in *FlattenRequest, opts ...grpc.CallOption) (*FlattenResponse, error)
	SubmitHumanApproval(ctx context.Context, in *SubmitApprovalRequest, opts ...grpc.CallOption) (*SubmitApprovalResponse, error)
	ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error)
}

type seKernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeKernelServiceClient(cc grpc.ClientConnInterface) SeKernelServiceClient {
	return &seKernelServiceClient{cc}
}

func (c *seKernelServiceClient) ExecuteStage(ctx context.Context, in *ExecuteStageRequest, opts ...grpc.CallOption) (*ExecuteStageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteStageResponse)
	err := c.cc.Invoke(ctx, SeKernelService_ExecuteStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seKernelServiceClient) ValidateContract(ctx context.Context, in *ValidateContractRequest, opts ...grpc.CallOption) (*ValidateContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateContractResponse)
	err := c.cc.Invoke(ctx, SeKernelService_ValidateContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seKernelServiceClient) FlattenToFrontend(ctx context.Context, in *FlattenRequest, opts ...grpc.CallOption) (*FlattenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlattenResponse)
	err := c.cc.Invoke(ctx, SeKernelService_FlattenToFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seKernelServiceClient) SubmitHumanApproval(ctx context.Context, in *SubmitApprovalRequest, opts ...grpc.CallOption) (*SubmitApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitApprovalResponse)
	err := c.cc.Invoke(ctx, SeKernelService_SubmitHumanApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seKernelServiceClient) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SeKernelService_ServiceDesc.Streams[0], SeKernelService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatStreamRequest, ChatStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SeKernelService_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamChunk]

type SeKernelServiceServer interface {
	ExecuteStage(context.Context, *ExecuteStageRequest) (*ExecuteStageResponse, error)
	ValidateContract(context.Context, *ValidateContractRequest) (*ValidateContractResponse, error)
	FlattenToFrontend(context.Context, *FlattenRequest) (*FlattenResponse, error)
	SubmitHumanApproval(context.Context, *SubmitApprovalRequest) (*SubmitApprovalResponse, error)
	ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error
	mustEmbedUnimplementedSeKernelServiceServer()
}

type UnimplementedSeKernelServiceServer struct{}

func (UnimplementedSeKernelServiceServer) ExecuteStage(context.Context, *ExecuteStageRequest) (*ExecuteStageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteStage not implemented")
}
func (UnimplementedSeKernelServiceServer) ValidateContract(context.Context, *ValidateContractRequest) (*ValidateContractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateContract not implemented")
}
func (UnimplementedSeKernelServiceServer) FlattenToFrontend(context.Context, *FlattenRequest) (*FlattenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlattenToFrontend not implemented")
}
func (UnimplementedSeKernelServiceServer) SubmitHumanApproval(context.Context, *SubmitApprovalRequest) (*SubmitApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHumanApproval not implemented")
}
func (UnimplementedSeKernelServiceServer) ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedSeKernelServiceServer) mustEmbedUnimplementedSeKernelServiceServer() {}
func (UnimplementedSeKernelServiceServer) testEmbeddedByValue()                         {}

type UnsafeSeKernelServiceServer interface {
	mustEmbedUnimplementedSeKernelServiceServer()
}

func RegisterSeKernelServiceServer(s grpc.ServiceRegistrar, srv SeKernelServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeKernelService_ServiceDesc, srv)
}

func _SeKernelService_ExecuteStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeKernelServiceServer).ExecuteStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeKernelService_ExecuteStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeKernelServiceServer).ExecuteStage(ctx, req.(*ExecuteStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeKernelService_ValidateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeKernelServiceServer).ValidateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeKernelService_ValidateContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeKernelServiceServer).ValidateContract(ctx, req.(*ValidateContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeKernelService_FlattenToFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlattenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeKernelServiceServer).FlattenToFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeKernelService_FlattenToFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeKernelServiceServer).FlattenToFrontend(ctx, req.(*FlattenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeKernelService_SubmitHumanApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeKernelServiceServer).SubmitHumanApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeKernelService_SubmitHumanApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeKernelServiceServer).SubmitHumanApproval(ctx, req.(*SubmitApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeKernelService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SeKernelServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatStreamRequest, ChatStreamChunk]{ServerStream: stream})
}

type SeKernelService_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamChunk]

var SeKernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seapp.SeKernelService",
	HandlerType: (*SeKernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteStage",
			Handler:    _SeKernelService_ExecuteStage_Handler,
		},
		{
			MethodName: "ValidateContract",
			Handler:    _SeKernelService_ValidateContract_Handler,
		},
		{
			MethodName: "FlattenToFrontend",
			Handler:    _SeKernelService_FlattenToFrontend_Handler,
		},
		{
			MethodName: "SubmitHumanApproval",
			Handler:    _SeKernelService_SubmitHumanApproval_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _SeKernelService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "se_app.proto",
}